version: "3"
services:
  cash-scheduler-db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: cash-scheduler-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "admin11@"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  cash-scheduler-client:
    image: ilyamatsuev/cash-scheduler-client
    build:
      context: ./src/client
      dockerfile: ./Dockerfile
    container_name: cash-scheduler-client
    stdin_open: true
    ports:
      - "3000:3000"

  cash-scheduler-server:
    image: ilyamatsuev/cash-scheduler-server
    build:
      context: ./src/server
      dockerfile: ./Dockerfile
    container_name: cash-scheduler-server
    depends_on:
      - cash-scheduler-db
    ports:
      - "8000:80"
      - "8001:443"
    env_file:
      - ./secrets.env
    environment:
      App__Db__Host: "cash-scheduler-db"
      App__Db__Port: "1433"
      App__Db__Name: "cash_scheduler"
      App__Db__Username: "SA"
      App__Db__Password: "admin11@"
      App__Db__Refresh: "true"
      App__Db__WithMockData: "false"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/ServerCert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
    volumes:
      - ./https:/https/
