type User {
    id: Int!
    first_name: String
    last_name: String
    email: String!
    password: String!
}

type Income {
    id: Int!
    title: String
    user: User!
    type: ActionType!
    amount: Float!
    date: String!
}

type Expense {
    id: Int!
    title: String
    user: User!
    type: ActionType!
    amount: Float!
    date: String!
}

type RecordType implements ActionType {
    type_name: String!
}

type CustomRecordType implements ActionType {
    type_name: String!
    user: User!
}

interface ActionType {
    type_name: String!
}


input NewUser {
    first_name: String
    last_name: String
    email: String!
    password: String!
}

input NewCustomRecordType {
    type_name: String!
}

input NewIncome {
    title: String
    type: String!
    amount: Float!
    date: String!
}

input NewExpense {
    title: String
    type: String!
    amount: Float!
    date: String!
}



type Query {
    getUserById(id: Int!): User!
    getUserByEmail(email: String!): User!
    getUsers: [User!]

    getRecordTypes: [RecordType!]

    getCustomRecordTypes: [CustomRecordType!]

    getAllIncome: [Income!]
    getIncomeByDate(date: String!): Income

    getAllExpenses: [Expense!]
    getExpenseByDate(date: String!): Expense
}

type Mutation {
    register(user: NewUser!): User!

    createCustomRecordType(customRecordType: NewCustomRecordType!): CustomRecordType!
    updateCustomRecordType(oldCustomTypeName: String!, newCustomType: NewCustomRecordType!): CustomRecordType!
    deleteCustomRecordType(customTypeName: String!): CustomRecordType!

    addIncome(income: NewIncome!): Income!
    editIncome(id: Int!, income: NewIncome!): Income!
    removeIncome(id: Int!): Income!

    addExpense(expense: NewExpense!): Expense!
    editExpense(id: Int!, expense: NewExpense!): Expense!
    removeExpense(id: Int!): Expense!
}
